"""Continuous real-time MT5/broker terminal reconciliation and fail-closed audit.

Monitors active broker positions against internal trade plans and ledger state.
If an untracked position, volume mismatch, or external manual trade is detected,
it trips the EmergencyStop circuit breaker and latches execution into
observation-only mode.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Awaitable, Callable, Iterable, Protocol

from broker.types import OrderSide, Position
from core.logger import logger
from execution.persistence import PositionLedgerEntry
from execution.models import IntentRecord, IntentRecordStatus, IntentRecordStore
from execution.safety import (
    DailyStateAuthority,
    EmergencyStopState,
    ExecutionAuthorization,
    ExecutionMode,
    ExecutionSafetySnapshot,
    SQLiteExecutionSafetyStore,
    utc_now,
)
from intelligence.trade_plan import TradePlan


class ReconciliationDiscrepancyType(str, Enum):
    """Categorized discrepancy found during continuous audit."""

    UNTRACKED_BROKER_POSITION = "UNTRACKED_BROKER_POSITION"
    EXTERNAL_MANUAL_TRADE = "EXTERNAL_MANUAL_TRADE"
    VOLUME_MISMATCH = "VOLUME_MISMATCH"
    SYMBOL_MISMATCH = "SYMBOL_MISMATCH"
    SIDE_MISMATCH = "SIDE_MISMATCH"
    PROTECTIVE_STOP_ALTERED = "PROTECTIVE_STOP_ALTERED"
    PHANTOM_INTERNAL_POSITION = "PHANTOM_INTERNAL_POSITION"
    BROKER_UNAVAILABLE = "BROKER_UNAVAILABLE"
    MALFORMED_BROKER_DATA = "MALFORMED_BROKER_DATA"


@dataclass(frozen=True, slots=True)
class ReconciliationDiscrepancy:
    """An auditable discrepancy between broker observation and internal state."""

    discrepancy_type: ReconciliationDiscrepancyType
    message: str
    symbol: str | None = None
    position_id: str | None = None
    broker_volume: float | None = None
    internal_volume: float | None = None
    detected_at: datetime = field(default_factory=utc_now)


@dataclass(frozen=True, slots=True)
class TrackedTradeState:
    """Internal canonical representation of an authorized open trade."""

    symbol: str
    side: OrderSide
    volume: float | None = None
    position_id: str | None = None
    order_id: str | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    magic_number: int | None = None
    source: str = "internal"

    @classmethod
    def from_trade_plan(
        cls,
        plan: TradePlan,
        *,
        position_id: str | None = None,
        order_id: str | None = None,
        volume: float | None = None,
        magic_number: int | None = None,
    ) -> TrackedTradeState:
        side_val = OrderSide.BUY if plan.signal == "BUY" else OrderSide.SELL
        return cls(
            symbol=plan.symbol.strip().upper(),
            side=side_val,
            volume=volume,
            position_id=str(position_id) if position_id is not None else None,
            order_id=str(order_id) if order_id is not None else None,
            stop_loss=plan.stop_loss,
            take_profit=plan.take_profit,
            magic_number=magic_number,
            source="trade_plan",
        )

    @classmethod
    def from_intent_record(cls, record: IntentRecord) -> TrackedTradeState | None:
        if record.symbol is None or record.side is None:
            return None
        side_val = (
            record.side if isinstance(record.side, OrderSide) else OrderSide(record.side)
        )
        vol = record.quantity.value if record.quantity is not None else None
        return cls(
            symbol=record.symbol.strip().upper(),
            side=side_val,
            volume=vol,
            position_id=str(record.order_id) if record.order_id is not None else None,
            order_id=str(record.order_id) if record.order_id is not None else None,
            stop_loss=record.stop_loss,
            take_profit=record.take_profit,
            source="intent_record",
        )

    @classmethod
    def from_ledger_entry(
        cls,
        entry: PositionLedgerEntry,
        *,
        side: OrderSide = OrderSide.BUY,
        volume: float | None = None,
    ) -> TrackedTradeState:
        return cls(
            symbol=entry.symbol.strip().upper(),
            side=side,
            volume=volume,
            position_id=str(entry.position_id),
            order_id=str(entry.order_id),
            source="ledger_entry",
        )


@dataclass(frozen=True, slots=True)
class AuditReconciliationReport:
    """Immutable report generated by a terminal reconciliation cycle."""

    reconciled_at: datetime
    broker: str
    is_clean: bool
    emergency_stop_tripped: bool
    discrepancies: tuple[ReconciliationDiscrepancy, ...]
    broker_positions_count: int
    tracked_positions_count: int
    action_taken: str


class PositionSourceGateway(Protocol):
    async def get_positions(self) -> list[Position] | list[object]: ...


class PositionLedgerSource(Protocol):
    def open_entries(self, *, broker: str) -> tuple[PositionLedgerEntry, ...]: ...


class TerminalReconciliationAuditor:
    """Evaluates active broker positions against internal state."""

    def __init__(
        self,
        gateway: PositionSourceGateway,
        *,
        broker: str = "weltrade",
        ledger: PositionLedgerSource | None = None,
        intent_store: IntentRecordStore | None = None,
        expected_magic_number: int | None = None,
    ) -> None:
        self.gateway = gateway
        self.broker = broker.strip().lower()
        self.ledger = ledger
        self.intent_store = intent_store
        self.expected_magic_number = expected_magic_number

    async def audit(
        self,
        *,
        active_plans: Iterable[TradePlan] | None = None,
        explicit_tracked: Iterable[TrackedTradeState] | None = None,
    ) -> AuditReconciliationReport:
        now = utc_now()
        discrepancies: list[ReconciliationDiscrepancy] = []

        # 1. Acquire broker positions
        try:
            raw_broker_positions = await self.gateway.get_positions()
            broker_positions: list[Position] = []
            for item in raw_broker_positions:
                if not isinstance(item, Position):
                    discrepancies.append(
                        ReconciliationDiscrepancy(
                            discrepancy_type=ReconciliationDiscrepancyType.MALFORMED_BROKER_DATA,
                            message=f"Received non-Position object from broker: {type(item).__name__}",
                            detected_at=now,
                        )
                    )
                else:
                    broker_positions.append(item)
        except Exception as exc:
            discrepancy = ReconciliationDiscrepancy(
                discrepancy_type=ReconciliationDiscrepancyType.BROKER_UNAVAILABLE,
                message=f"Failed to query active positions from broker '{self.broker}': {exc}",
                detected_at=now,
            )
            return AuditReconciliationReport(
                reconciled_at=now,
                broker=self.broker,
                is_clean=False,
                emergency_stop_tripped=False,
                discrepancies=(discrepancy,),
                broker_positions_count=0,
                tracked_positions_count=0,
                action_taken="AUDIT_FAILED",
            )

        # 2. Gather internal tracked trade state
        tracked_map: dict[str, TrackedTradeState] = {}
        tracked_by_symbol: dict[str, list[TrackedTradeState]] = {}

        def _add_tracked(trade: TrackedTradeState) -> None:
            if trade.position_id is not None:
                tracked_map[trade.position_id] = trade
            tracked_by_symbol.setdefault(trade.symbol, []).append(trade)

        if explicit_tracked is not None:
            for t in explicit_tracked:
                _add_tracked(t)

        if active_plans is not None:
            for plan in active_plans:
                _add_tracked(TrackedTradeState.from_trade_plan(plan))

        if self.ledger is not None:
            try:
                for entry in self.ledger.open_entries(broker=self.broker):
                    _add_tracked(TrackedTradeState.from_ledger_entry(entry))
            except Exception as exc:
                logger.warning("Could not read ledger entries for audit: {}", exc)

        if self.intent_store is not None:
            try:
                for record in self.intent_store.list_unresolved():
                    if record.status is IntentRecordStatus.ACCEPTED:
                        t = TrackedTradeState.from_intent_record(record)
                        if t is not None:
                            _add_tracked(t)
            except Exception as exc:
                logger.warning("Could not read intent records for audit: {}", exc)

        # 3. Reconcile broker positions against internal tracked trades
        matched_tracked_keys: set[str] = set()

        for b_pos in broker_positions:
            pid = str(b_pos.position_id)
            symbol = b_pos.symbol.strip().upper()
            tracked_match: TrackedTradeState | None = None

            # Primary match: by exact position ID
            if pid in tracked_map:
                tracked_match = tracked_map[pid]
                matched_tracked_keys.add(pid)
            elif symbol in tracked_by_symbol and tracked_by_symbol[symbol]:
                # Fallback match: if symbol matches an internal trade without explicit position ID
                unmatched = [
                    t for t in tracked_by_symbol[symbol]
                    if t.position_id is None or t.position_id not in matched_tracked_keys
                ]
                if unmatched:
                    tracked_match = unmatched[0]
                    if tracked_match.position_id is not None:
                        matched_tracked_keys.add(tracked_match.position_id)

            if tracked_match is None:
                # Untracked external or manual position found!
                disc_type = (
                    ReconciliationDiscrepancyType.EXTERNAL_MANUAL_TRADE
                    if self.expected_magic_number is not None
                    and getattr(b_pos, "magic", None) != self.expected_magic_number
                    else ReconciliationDiscrepancyType.UNTRACKED_BROKER_POSITION
                )
                discrepancies.append(
                    ReconciliationDiscrepancy(
                        discrepancy_type=disc_type,
                        symbol=symbol,
                        position_id=pid,
                        broker_volume=b_pos.volume,
                        message=(
                            f"Active broker position {pid} on '{symbol}' (volume={b_pos.volume}) "
                            f"is not tracked in internal JQE state."
                        ),
                        detected_at=now,
                    )
                )
                continue

            # Verify Symbol
            if symbol != tracked_match.symbol:
                discrepancies.append(
                    ReconciliationDiscrepancy(
                        discrepancy_type=ReconciliationDiscrepancyType.SYMBOL_MISMATCH,
                        symbol=symbol,
                        position_id=pid,
                        message=f"Position {pid} symbol mismatch: broker='{symbol}', tracked='{tracked_match.symbol}'",
                        detected_at=now,
                    )
                )

            # Verify Side
            if b_pos.side != tracked_match.side:
                discrepancies.append(
                    ReconciliationDiscrepancy(
                        discrepancy_type=ReconciliationDiscrepancyType.SIDE_MISMATCH,
                        symbol=symbol,
                        position_id=pid,
                        message=f"Position {pid} side mismatch: broker='{b_pos.side.value}', tracked='{tracked_match.side.value}'",
                        detected_at=now,
                    )
                )

            # Verify Volume
            if tracked_match.volume is not None:
                if abs(float(b_pos.volume) - float(tracked_match.volume)) > 1e-4:
                    discrepancies.append(
                        ReconciliationDiscrepancy(
                            discrepancy_type=ReconciliationDiscrepancyType.VOLUME_MISMATCH,
                            symbol=symbol,
                            position_id=pid,
                            broker_volume=float(b_pos.volume),
                            internal_volume=float(tracked_match.volume),
                            message=(
                                f"Position {pid} volume mismatch on '{symbol}': "
                                f"broker={b_pos.volume}, internal={tracked_match.volume}"
                            ),
                            detected_at=now,
                        )
                    )

            # Verify Magic Number if configured
            if self.expected_magic_number is not None:
                pos_magic = getattr(b_pos, "magic", None)
                if pos_magic is not None and pos_magic != self.expected_magic_number:
                    discrepancies.append(
                        ReconciliationDiscrepancy(
                            discrepancy_type=ReconciliationDiscrepancyType.EXTERNAL_MANUAL_TRADE,
                            symbol=symbol,
                            position_id=pid,
                            message=(
                                f"Position {pid} magic number mismatch: "
                                f"broker={pos_magic}, expected={self.expected_magic_number}"
                            ),
                            detected_at=now,
                        )
                    )

        # 4. Check for phantom internal positions (internal claims open, but absent on broker)
        for pid, t_pos in tracked_map.items():
            if pid not in matched_tracked_keys and t_pos.position_id is not None:
                # If it had an explicit position_id and wasn't found in broker_positions:
                discrepancies.append(
                    ReconciliationDiscrepancy(
                        discrepancy_type=ReconciliationDiscrepancyType.PHANTOM_INTERNAL_POSITION,
                        symbol=t_pos.symbol,
                        position_id=pid,
                        internal_volume=t_pos.volume,
                        message=(
                            f"Internal tracked position {pid} on '{t_pos.symbol}' "
                            f"is absent from active broker positions."
                        ),
                        detected_at=now,
                    )
                )

        is_clean = len(discrepancies) == 0
        return AuditReconciliationReport(
            reconciled_at=now,
            broker=self.broker,
            is_clean=is_clean,
            emergency_stop_tripped=False,
            discrepancies=tuple(discrepancies),
            broker_positions_count=len(broker_positions),
            tracked_positions_count=len(tracked_map),
            action_taken="CLEAN" if is_clean else "DISCREPANCIES_DETECTED",
        )


class ContinuousTerminalReconciliationService:
    """Circuit-breaking continuous monitor and safety enforcement service."""

    def __init__(
        self,
        auditor: TerminalReconciliationAuditor,
        *,
        safety_store: SQLiteExecutionSafetyStore | None = None,
        settings: Any | None = None,
        on_circuit_break: Callable[[AuditReconciliationReport], Awaitable[None]] | None = None,
        environment: str = "demo",
    ) -> None:
        self.auditor = auditor
        self.safety_store = safety_store
        self.settings = settings
        self.on_circuit_break = on_circuit_break
        self.environment = environment
        self._running = False
        self._last_report: AuditReconciliationReport | None = None
        self._emergency_stop_latched = False

    @property
    def is_emergency_stop_latched(self) -> bool:
        return self._emergency_stop_latched

    @property
    def last_report(self) -> AuditReconciliationReport | None:
        return self._last_report

    async def reconcile_and_protect(
        self,
        *,
        active_plans: Iterable[TradePlan] | None = None,
        explicit_tracked: Iterable[TrackedTradeState] | None = None,
    ) -> AuditReconciliationReport:
        """Run a single audit evaluation and trigger circuit breaker if unclean."""
        report = await self.auditor.audit(
            active_plans=active_plans, explicit_tracked=explicit_tracked
        )
        self._last_report = report

        if not report.is_clean:
            # Trip the fail-closed circuit breaker
            self._emergency_stop_latched = True
            action_reasons = tuple(d.discrepancy_type.value for d in report.discrepancies)
            logger.critical(
                "TERMINAL RECONCILIATION BREACH! Tripping EmergencyStop. Reasons: {}",
                action_reasons,
            )

            # 1. Update settings if available
            if self.settings is not None:
                self.settings.emergency_stop = EmergencyStopState.ACTIVE
                self.settings.broker_execution_enabled = False

            # 2. Persist to SQLite safety store
            if self.safety_store is not None:
                try:
                    self.safety_store.publish(
                        ExecutionSafetySnapshot(
                            observed_at=report.reconciled_at,
                            emergency_stop_state=EmergencyStopState.ACTIVE,
                            execution_mode=ExecutionMode.DURABLE,
                            broker=self.auditor.broker,
                            environment=self.environment,
                            durable_executor_enabled=False,
                            daily_state_authority=DailyStateAuthority.AUTHORITATIVE,
                            unresolved_intent_count=len(report.discrepancies),
                            unresolved_intent_blocked=True,
                            execution_authorization=ExecutionAuthorization.BLOCKED,
                            reason_codes=action_reasons,
                        )
                    )
                except Exception as exc:
                    logger.error("Failed to publish safety snapshot during breach: {}", exc)

            # 3. Fire optional notification callback
            if self.on_circuit_break is not None:
                try:
                    await self.on_circuit_break(report)
                except Exception as exc:
                    logger.error("Error in on_circuit_break handler: {}", exc)

            report = AuditReconciliationReport(
                reconciled_at=report.reconciled_at,
                broker=report.broker,
                is_clean=False,
                emergency_stop_tripped=True,
                discrepancies=report.discrepancies,
                broker_positions_count=report.broker_positions_count,
                tracked_positions_count=report.tracked_positions_count,
                action_taken="EMERGENCY_STOP_TRIPPED",
            )
            self._last_report = report

        return report

    async def run_loop(
        self,
        poll_interval_seconds: float = 2.0,
        stop_event: asyncio.Event | None = None,
        *,
        active_plans_provider: Callable[[], Iterable[TradePlan]] | None = None,
        explicit_tracked_provider: Callable[[], Iterable[TrackedTradeState]] | None = None,
    ) -> None:
        """Run background continuous audit loop until stop_event or cancellation."""
        self._running = True
        logger.info(
            "Starting continuous terminal reconciliation monitor (broker={}, interval={}s)",
            self.auditor.broker,
            poll_interval_seconds,
        )
        try:
            while self._running:
                if stop_event is not None and stop_event.is_set():
                    break

                plans = active_plans_provider() if active_plans_provider is not None else None
                tracked = explicit_tracked_provider() if explicit_tracked_provider is not None else None

                report = await self.reconcile_and_protect(
                    active_plans=plans, explicit_tracked=tracked
                )

                if report.emergency_stop_tripped:
                    logger.warning(
                        "Continuous audit monitor latched in EMERGENCY_STOP. Halting further checks."
                    )
                    break

                await asyncio.sleep(poll_interval_seconds)
        except asyncio.CancelledError:
            logger.info("Continuous terminal reconciliation monitor cancelled.")
            raise
        finally:
            self._running = False
            logger.info("Continuous terminal reconciliation monitor stopped.")

    def stop(self) -> None:
        self._running = False
