"""Broker-independent contract lifecycle states."""

from enum import Enum


class ContractLifecycleState(str, Enum):
    SUBMISSION_UNKNOWN = "SUBMISSION_UNKNOWN"
    PROPOSED = "PROPOSED"
    PURCHASED_OPEN = "PURCHASED_OPEN"
    SELLABLE = "SELLABLE"
    CLOSE_REQUESTED = "CLOSE_REQUESTED"
    CLOSED = "CLOSED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
    BROKER_STATE_UNAVAILABLE = "BROKER_STATE_UNAVAILABLE"
